### ISSUE TITLE
Angela Jet addiction

### ISSUE THREAD

**Issue by burner1024** [NovaRain/Fallout2_Unofficial_Patch#1]
I was working on implementing [Jet addiction from Angela](https://github.com/BGforgeNet/fo2tweaks/issues/17)... and found out that it's actually already [there](https://github.com/NovaRain/FO2_UP_postfix/blob/master/scripts_src/NEWRENO/NCANGBIS.SSL#L326). But it doesn't work. Looks like the same fallacy as Ms. Kitty's bonuses, use_obj_on_obj requires the object to be near?

I suspect that grepping by this function may reveal a few problems of the same nature.

**Comment by NovaRain** [comment]
RP fixed Ms. Kitty's bonuses by using MVAR and critter_p_proc. Angela's Jet should be handled in the same way.

**Comment by burner1024** [comment]
fixed
